# Generated by Django 3.2.13 on 2022-05-18 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0002_alter_task_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='member',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
